# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Documents\File Manager with ML\Pop-up_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 379)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 581, 331))
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setObjectName("textEdit")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(80, 0, 226, 22))
        self.fontComboBox.setWritingSystem(QtGui.QFontDatabase.Any)
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.AllFonts)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.fontComboBox.setCurrentFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(410, 0, 42, 22))
        self.spinBox.setMinimum(5)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.font_label = QtWidgets.QLabel(self.centralwidget)
        self.font_label.setGeometry(QtCore.QRect(0, 0, 71, 21))
        self.font_label.setScaledContents(True)
        self.font_label.setObjectName("font_label")
        self.font_size_label = QtWidgets.QLabel(self.centralwidget)
        self.font_size_label.setGeometry(QtCore.QRect(310, 0, 131, 21))
        self.font_size_label.setObjectName("font_size_label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(500, 0, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.font_style_label = QtWidgets.QLabel(self.centralwidget)
        self.font_style_label.setGeometry(QtCore.QRect(450, 0, 55, 16))
        self.font_style_label.setScaledContents(True)
        self.font_style_label.setWordWrap(True)
        self.font_style_label.setIndent(5)
        self.font_style_label.setObjectName("font_style_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 350, 295, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout.addWidget(self.clear_button)
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSelect_Font = QtWidgets.QAction(MainWindow)
        self.actionSelect_Font.setObjectName("actionSelect_Font")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.font_label.setText(_translate("MainWindow", "Select Font"))
        self.font_size_label.setText(_translate("MainWindow", "Select Font Size"))
        self.font_style_label.setText(_translate("MainWindow", "Style"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.actionSelect_Font.setText(_translate("MainWindow", "Select Font"))
